language: php

php:
  - 7.0
  - 7.1

matrix:
  include:
    - php: 7.0
      env: ZF_VERSION=2
    - php: 7.1
      env: ZF_VERSION=2
  fast_finish: true

before_install:
  - cp $HOME/.phpenv/versions/$(phpenv global)/etc/conf.d/xdebug.ini /tmp
  - phpenv config-rm xdebug.ini
  - if [ "$ZF_VERSION" = "2" ]; then sed 's/ | ^3.0//g' composer.json > composer_v27.json; rm composer.json; mv composer_v27.json composer.json; fi

install:
  - composer install --no-progress --no-interaction --prefer-dist --no-suggest

script:
  - phpenv config-add /tmp/xdebug.ini
  - mkdir -p build/logs
  - vendor/phpunit/phpunit/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls -v

cache:
    directories:
        - $HOME/.composer/cache

notifications:
  email: false