language: php

php:
  - 7.0
  - nightly
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - composer update --no-interaction --prefer-dist --no-suggest

script:
  - phpunit

notifications:
  email: false