language: php

php:
  - 7.0

matrix:
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - composer install --dev --no-interaction --prefer-dist --no-suggest

script:
  - mkdir -p build/logs
  - vendor/phpunit/phpunit/phpunit -c phpunit.xml

after_success:
  - travis_retry php vendor/bin/coveralls

notifications:
  email: false